.apex/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Deluxe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Clothing</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Furniture</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/ItemService.cls
public with sharing class ItemService {

	@AuraEnabled(cacheable=true)
	public static List<Item__c> getItems(
			String family,
			String type,
			String searchKey
			) {
		String searchPattern = '%' + searchKey + '%';

		String soql =
				'SELECT Id, Name, Description__c, Type__c, Family__c, Price__c, Image__c ' +
				'FROM Item__c ' +
				'WHERE 1 = 1';

		if (String.isNotBlank(family)) {
			soql += ' AND Family__c = :family';
		}

		if (String.isNotBlank(type)) {
			soql += ' AND Type__c = :type';
		}

		if (String.isNotBlank(searchKey)) {
			soql += ' AND (Name LIKE :searchPattern OR Description__c LIKE :searchPattern)';
		}

		soql += ' ORDER BY Name';

		return Database.query(soql);
	}

	@AuraEnabled(cacheable=true)
	public static List<String> getTypes() {
		Schema.DescribeFieldResult fieldResult = Item__c.Type__c.getDescribe();
		List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
		List<String> types = new List<String>();
		for (Schema.PicklistEntry pe : picklistValues) {
			types.add(pe.getValue());
		}
		return types;
	}

	@AuraEnabled(cacheable=true)
	public static List<String> getFamilies() {
		Schema.DescribeFieldResult fieldResult = Item__c.Family__c.getDescribe();
		List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
		List<String> families = new List<String>();
		for (Schema.PicklistEntry pe : picklistValues) {
			families.add(pe.getValue());
		}
		return families;
	}

}