.apex/src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ClientId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purchase__c</fullName>
        <label>Purchase</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>PurchaseLines</relationshipLabel>
        <relationshipName>PurchaseLines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>UnitCost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseLine</label>
    <nameField>
        <label>PurchaseLine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/src/classes/PurchaseService.cls
public with sharing class PurchaseService {

	@AuraEnabled
	public static Id checkout(Id accountId, String cartItemsJson){
		if (accountId == null) {
			throw new AuraHandledException('Account is required');
		}

		List<CartItemDTO> cartItems = (List<CartItemDTO>) JSON.deserialize(cartItemsJson, List<CartItemDTO>.class);

		if (cartItems == null || cartItems.isEmpty()) {
			throw new AuraHandledException('Cart is empty');
		}

		System.debug('===============================purchase.Id: ' + cartItems[0]);

		Purchase__c purchase = new Purchase__c(
				Name = 'Purchase ' + Datetime.now().format('yyyyMMdd-HHmmss'),
				ClientId__c = accountId);
		insert purchase;

		List<PurchaseLine__c> lines = new List<PurchaseLine__c>();

		for (CartItemDTO ci : cartItems) {
			lines.add(new PurchaseLine__c(
					PurchaseId__c = purchase.Id,
					ItemId__c = ci.itemId,
					Amount__c = ci.quantity,
					UnitCost__c = ci.price
			));
		}

		insert lines;

		System.debug('===============================purchase.Id: ' + purchase.Id);
		return purchase.Id;
	}

	public class CartItemDTO {
		@AuraEnabled public Id itemId;
		@AuraEnabled public Integer quantity;
		@AuraEnabled public Decimal price;
	}
}